---
# tasks/main.yml file for ansible-nifi
- include_tasks: ./base/{{ ansible_os_family }}.yml

- name: create /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    mode: 0644
    unsafe_writes: "{{ ansible_virtualization_type == 'docker' }}"
  when: create_etc_hosts | default("yes", true) | bool

- name: set nofile ulimit to {{ pam_limits_nofile }}
  pam_limits:
    domain: '*'
    limit_type: "{{ item }}"
    limit_item: nofile
    value: "{{ pam_limits_nofile }}"
    use_max: yes
  with_items:
    - hard
    - soft

- name: set nproc ulimit to {{ pam_limits_nproc }}
  pam_limits:
    domain: '*'
    limit_type: "{{ item }}"
    limit_item: nproc
    value: "{{ pam_limits_nproc }}"
    use_max: yes
  with_items:
    - hard
    - soft

- name: set net.ipv4.ip_local_port_range={{ net_ipv4_ip_local_port_range }}
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: "{{ net_ipv4_ip_local_port_range }}"
    sysctl_set: yes
    state: present
    reload: yes
  when: ansible_virtualization_type != "docker"

- name: set vm.swapiness={{ vm_swapiness }}
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^vm.swapiness='
    line: vm.swapiness={{ vm_swapiness }}

- include_tasks: ./java/{{ ansible_os_family }}.yml

# See https://www.java.com/en/configure_crypto.html
- name: force TLSv1.2 with java
  block:
    - name: set java_security_file
      set_fact:
        java_security_file: "{{ java_home }}/{{ (java_version|string == '1.8' or java_version|string == '1.8.0' or java_version|string == '8') | ternary('jre/lib/security/java.security', 'conf/security/java.security') }}"
        cacheable: yes

    - name: check for TLSv1, TLSv1.1 in java.security file
      shell: grep -Pzo '(?sm)^jdk\.tls\.disabledAlgorithms=.*?(?<!\\)\n' {{ java_security_file }} | grep -Pz '\b{{ item | regex_escape }}(\s*,\s*|\Z)'
      register: grep_result
      with_items: ["TLSv1", "TLSv1.1"]
      failed_when: grep_result.rc > 1 or grep_result.stderr|length > 0
      changed_when: grep_result.rc == 1

    - name: disable TLSv1, TLSv1.1
      replace:
        path: "{{ java_security_file }}"
        regexp: '(?sm)^jdk\.tls\.disabledAlgorithms=(.*?)(?<!\\)\n'
        replace: 'jdk.tls.disabledAlgorithms=\1, {{ item }}\n'
        backup: yes
      with_items: "{{ grep_result.results | selectattr('rc', 'equalto', 1) | map(attribute='item') | list }}"
  when: force_tls_v1_2 | default("yes", true) | bool

- name: set java random source to /dev/urandom
  lineinfile:
    dest: "{{ java_security_file }}"
    regexp: '^securerandom\.source=.*$'
    line: 'securerandom.source=file:/dev/urandom'
    backup: yes

- name: create /etc/profile.d/java.sh
  template:
    src: templates/java.sh.j2
    dest: /etc/profile.d/java.sh
    mode: 0644

- include_tasks: ./nifi/common.yml

- name: set nifi_cluster
  set_fact:
    nifi_cluster: nifi_cluster | default("no", true) | bool
    cacheable: yes

- include_tasks: ./nifi/{{ nifi_cluster | bool | ternary("cluster", "standalone") }}.yml

- name: set zookeeper_install_type
  set_fact:
    zookeeper_install_type: "{% if nifi_cluster|bool and (zookeeper_install|bool or zookeeper_install == 'local') %}local{% elif nifi_cluster|bool and zookeeper_install|default('embedded', true) == 'embedded' %}embedded{% else %}none{% endif %}"
    cacheable: yes

- include_tasks: ./zookeeper/{{ zookeeper_install_type }}.yml
  when: nifi_cluster|bool

- name: set supervisord_install
  set_fact:
    supervisord_install: "{{ ansible_virtualization_type == 'docker' }}"
    cacheable: yes

# For some reason include* can't resolve ansible_virtualization_type so we set
# supervisord_install above so we can do the conditional include like so.
- include_tasks: ./init/{{ supervisord_install | ternary("supervisord", "systemd" ) }}.yml
