---
# tasks/zookeeper/embedded.yml file for ansible-nifi
- name: setup embedded zookeeper
  block:
    - name: set enable embedded zookeeper to true in ./conf/nifi.properties
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: '^nifi\.state\.management\.embedded\.zookeeper\.start='
        line: nifi.state.management.embedded.zookeeper.start=true
    - name: add server entries to ./conf/zookeeper.properties
      lineinfile:
        path: "{{ nifi_home }}/conf/zookeeper.properties"
        regexp: '^server\.{{ item.0 + 1 }}='
        line: "server.{{ item.0 + 1 }}={{ item.1 }}:{{ zookeeper_server_ports }};{{ zookeeper_client_port }}"
      with_indexed_items: "{{ ansible_play_hosts | map('extract', hostvars, 'ansible_hostname') | list }}"
    - name: create ./state/zookeeper directory
      file:
        path: "{{ nifi_home }}/state/zookeeper"
        state: directory
        owner: "{{ nifi_run_as }}"
        group: "{{ nifi_run_as }}"
        mode: 0755
    - name: set zookeeper id in ./state/zookeeper/myid
      copy:
        content: "{{ ansible_play_hosts.index(inventory_hostname) + 1 }}"
        dest: "{{ nifi_home }}/state/zookeeper/myid"
        mode: 0644
        owner: "{{ nifi_run_as }}"
        group: "{{ nifi_run_as }}"
  when: nifi_cluster|bool and zookeeper_install == "embedded"
