---
# tasks/zookeeper/zookeeper.yml file for ansible-nifi
- name: install local zookeeper
  block:
    - name: get closest apache mirror for zookeeper
      uri:
        url: "{{ apache_mirror_info_url }}/zookeeper/{{ zookeeper_version }}?as_json{{ not apache_mirror_info_country_codes | ternary('', '&cca2=' + apache_mirror_info_country_codes) }}"
        return_content: yes
      register: zookeeper_mirror_info
      until: zookeeper_mirror_info.status == 200
      retries: 5
      delay: 1
      when: not package_base_url

    - name: set zookeeper package base url
      set_fact:
        zookeeper_package_base_url: "{{ zookeeper_mirror_info.json.in_dist | ternary(zookeeper_mirror_info.json.preferred, apache_archive_url) }}{{ zookeeper_mirror_info.json.path_info }}"
        cacheable: yes
      when: not package_base_url

    - name: set zookeeper package url
      set_fact:
        zookeeper_package_url: "{{ zookeeper_package_base_url | default(package_base_url, true) }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
        cacheable: yes

    - name: create zookeeper install directory
      file:
        path: "{{ zookeeper_install_prefix }}"
        state: directory

    - name: fetch {{ zookeeper_package_url }}
      unarchive:
        src: "{{ zookeeper_package_url }}"
        dest: "{{ zookeeper_install_prefix }}"
        creates: "{{ zookeeper_install_prefix }}/zookeeper-{{ zookeeper_version }}"
        remote_src: yes
        extra_opts:
          - --no-same-owner
          - --transform
          - s/^apache-zookeeper-{{ zookeeper_version }}-bin/zookeeper-{{ zookeeper_version }}/

    - name: create symlink to {{ zookeeper_install_prefix }}/zookeeper
      file:
        src: "{{ zookeeper_install_prefix }}/zookeeper-{{ zookeeper_version }}"
        dest: "{{ zookeeper_install_prefix }}/zookeeper"
        state: link

    - name: create zookeeper data directory
      file:
        path: "{{ zookeeper_install_prefix }}/zookeeper-{{ zookeeper_version }}/data"
        state: directory

    - name: set zookeeper id
      copy:
        content: "{{ ansible_play_hosts.index(inventory_hostname) + 1 }}"
        dest: "{{ zookeeper_install_prefix }}/zookeeper-{{ zookeeper_version }}/data/myid"
        mode: 0644

    - name: setup zookeeper ./conf/zoo.cfg
      template:
        src: templates/zoo.cfg.j2
        dest: "{{ zookeeper_install_prefix }}/zookeeper/conf/zoo.cfg"
        mode: 0644
  when: zookeeper_install|bool or zookeeper_install == "local"
