---
# tasks/java/Debian.yml file for ansible-nifi
- name: install java (debian)
  block:
    - name: set java version
      set_fact:
        java_version: "{% if java_version|string == '1.8' or java_version|string == '1.8.0' %}8{% else %}{{ java_version }}{% endif %}"
      tags: [java, zookeeper]

    - name: install java {{ java_version }}
      apt:
        name: openjdk-{{ java_version }}-jre-headless
        state: present
      when: ansible_os_family == "Debian"
      tags: [java, zookeeper]

    - name: set java_home
      set_fact:
        java_home: "{{ '/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64' | realpath }}"
      tags: [java, zookeeper]

    - name: set default java alternative
      alternatives:
        name: java
        path: "{{ java_home }}/bin/java"
      tags: [java, zookeeper]
  when: ansible_os_family == "Debian"
